name: Deploy to Vercel

on:
  push:
    branches:
      - main  # Change to your branch name if needed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Authenticate Vercel
        run: vercel login --token ${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Project
        run: vercel --prod --yes --token ${{ secrets.VERCEL_TOKEN }}
