name: Deploy to Vercel

on:
  push:
    branches:
      - main  # Change this if deploying from another branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Authenticate with Vercel
        run: vercel login --token ${{ secrets.VERCEL_TOKEN }}

      - name: Deploy to Vercel
        run: vercel --prod --token ${{ secrets.VERCEL_TOKEN }}
